apiVersion: v1
kind: Pod                                            
metadata:
  name: kube-h6-p2
  namespace: pavlo-teslenko
  labels:
    app: pod
spec:                                                
  containers:
    - image: paullol/ma.devops.teslenko.private:part2
      name: myapp-1
      env:
      - name: PORT
        valueFrom:
          secretKeyRef:
            name: port
            key: PORT  
  imagePullSecrets:
    - name: dockerlogin                         
  restartPolicy: Never


